spring:
  application:
    name: the-open-book
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/opendb
    username: postgres
    password: changeme
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Threshold for file uploading
servelet:
  multipart:
    max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  servelet:
    context-path: /api/v1/
