spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/opendb
    username: postgres
    password: changeme
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics=true


  #     prorperties:
  #       hibernate:
  #         format-sql: true
  #       database: postgresql
  #       database-platform: org.hibernate.dialect.PostgreSLDialect
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework:
        web: DEBUG
      org.hibernate:
        stat: debug

  mail:
    host: localhost
    port: 1025
    username: appuser
    password: verysecret
    prorperties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connecitontimout: 5000
        timeout: 3000
        writetimeout: 5000
  management:
    httpexchanges:
      recording:
        enabled: true
    endpoints:
      web:
        exposure:
          include: beans,health,info,metrics




server:
  servlet:
    context-path: /api/v1
  port: 8080
